### ISSUE TITLE
very good work! codes?

### ISSUE THREAD

**Issue by ZhangGongjie** [dk-liang/UniSeg3D#1]
When can we see the codes? I am looking forward to that! :)

**Comment by chunshengshi** [comment]
Thanks for your attention. We are organizing the codes, may be 1~2 weeks later.

**Comment by chunshengshi** [comment]
> When can we see the codes? I am looking forward to that! :)

Thanks for your attention. We are organizing the codes, may be 1~2 weeks later.

**Comment by chunshengshi** [comment]
> When can we see the codes? I am looking forward to that! :)

Hi~Thank you for your patience. The inference code and checkpoints have been released.

**Comment by dk-liang** [comment]
Released. If you find this repository useful in your research, please consider giving a star ⭐
