### ISSUE TITLE
Dataset 这一步骤中缺少文件

### ISSUE THREAD

**Issue by Robotmaid** [dk-liang/UniSeg3D#2]
![1](https://github.com/user-attachments/assets/3ec60bf9-1788-4115-92e2-7933cfd0356a)
可下载的文件中没有`batch_load_scannet_data.py`文件

**Comment by Robotmaid** [comment]
已解决，需要去`https://github.com/open-mmlab/mmdetection3d/blob/1.0/data/scannet/`中下载源代码后加入到项目的`/data/scannet/`中
`pip install git+https://github.com/open-mmlab/mmdetection3d.git@fe25f7a51d36e3702f961e198894580d83c4387b
`这一步骤并没有将源代码加入到项目中

**Comment by xuweigogogo** [comment]
> 已解决，需要去`https://github.com/open-mmlab/mmdetection3d/blob/1.0/data/scannet/`中下载源代码后加入到项目的`/data/scannet/`中 `pip install git+https://github.com/open-mmlab/mmdetection3d.git@fe25f7a51d36e3702f961e198894580d83c4387b `这一步骤并没有将源代码加入到项目中

感谢您的努力，我们在[本次提交中](https://github.com/dk-liang/UniSeg3D/tree/025b5ff1cae3743d5dc953e0639210b4b7146a78)上传了`data/scannet`文件夹，其中包含了数据处理所必须的文件。
