### ISSUE TITLE
请问mmdet3d具体是哪个版本的？

### ISSUE THREAD

**Issue by jweden33** [dk-liang/UniSeg3D#4]
我在复现的过程中遇到了这个报错：
KeyError: 'UniSeg3D is not in the mmdet3d::model registry. Please check whether the value of `UniSeg3D` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16649) of binary: /root/miniconda/envs/uniseg3d/bin/python
Traceback (most recent call last):
请问该如何解决

**Comment by chunshengshi** [comment]
> 我在复现的过程中遇到了这个报错： KeyError: 'UniSeg3D is not in the mmdet3d::model registry. Please check whether the value of `UniSeg3D` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module' ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16649) of binary: /root/miniconda/envs/uniseg3d/bin/python Traceback (most recent call last): 请问该如何解决

请问您是在哪个步骤遇到这个问题

**Comment by jweden33** [comment]
> > 我在复现的过程中遇到了这个报错： KeyError: 'UniSeg3D is not in the mmdet3d::model registry. Please check whether the value of `UniSeg3D` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module' ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16649) of binary: /root/miniconda/envs/uniseg3d/bin/python Traceback (most recent call last): 请问该如何解决
> 
> 请问您是在哪个步骤遇到这个问题

就是在运行推理脚本的时候

**Comment by chunshengshi** [comment]
> > > 我在复现的过程中遇到了这个报错： KeyError: 'UniSeg3D is not in the mmdet3d::model registry. Please check whether the value of `UniSeg3D` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module' ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16649) of binary: /root/miniconda/envs/uniseg3d/bin/python Traceback (most recent call last): 请问该如何解决
> > 
> > 
> > 请问您是在哪个步骤遇到这个问题
> 
> 就是在运行推理脚本的时候

我们安装的mmdet3d版本为`1.4.0`，但是我们认为您遇到的问题应该和mmdet3d的版本没有直接关联。我们暂时没有办法复现您的问题，不能给出直接的解决方案。

我们猜测您有可能在非本仓库的路径下运行了推理命令，注意inference步骤需要到`UniSeg3D/`路径下运行。如果没有解决您的问题，可以提供更详细的问题信息，我们会进一步讨论解决。

**Comment by bongShen** [comment]
请问必须要把数据集全下载下来吗？我只想使用一个场景看一下效果，例如scene0000_01，我已经修改了scannetv2_val.txt文件，但是代码还会按照之前的设计寻找？请问一下我该如何修改？
![image](https://github.com/user-attachments/assets/0729c10b-ba19-4580-917c-81118c025e2c)
