### ISSUE TITLE
测试一个场景，需要下载全部数据集吗？

### ISSUE THREAD

**Issue by bongShen** [dk-liang/UniSeg3D#6]
请问必须要把数据集全下载下来吗？我只想使用一个场景看一下效果，例如scene0000_01，我已经修改了scannetv2_val.txt文件，但是代码还会按照之前的设计寻找？请问一下我该如何修改？
![image](https://github.com/user-attachments/assets/106b0d7c-82e0-49f8-aaf3-d2cc7553ee5a)

**Comment by xuweigogogo** [comment]
> 请问必须要把数据集全下载下来吗？我只想使用一个场景看一下效果，例如scene0000_01，我已经修改了scannetv2_val.txt文件，但是代码还会按照之前的设计寻找？请问一下我该如何修改？ ![image](https://private-user-images.githubusercontent.com/101329767/381373487-106b0d7c-82e0-49f8-aaf3-d2cc7553ee5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODUyMzAsIm5iZiI6MTczMDk4NDkzMCwicGF0aCI6Ii8xMDEzMjk3NjcvMzgxMzczNDg3LTEwNmIwZDdjLTgyZTAtNDlmOC1hYWYzLWQyY2M3NTUzZWU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxMzA4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDcxZDZiZjlmNGIzODU1MDA0YzI3YWFlNTcxODU5YjliOGJmMzU0Njg5NGE5OWM4ZWM2NGQwYmQ3YjQxYTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kxa8a6VsLgF3VDqeh9b4sDVlsMJAtRGc9t9bDvEmKdo)

您可以考虑编辑`uniseg3d_infos_val.pkl`文件，仅保留将要测试的场景信息
