### ISSUE TITLE
Can you share how to make uniseg3d_infos_train.pkl?

### ISSUE THREAD

**Issue by hxiaoj** [dk-liang/UniSeg3D#8]

**Comment by xuweigogogo** [comment]
We take the following steps to make `uniseg3d_infos_train.pkl`:
1) Uncomment lines:

https://github.com/dk-liang/UniSeg3D/blob/470854df3afee2e9d0494e3b436ed677eded4b52/tools/indoor_converter.py#L34-L35

https://github.com/dk-liang/UniSeg3D/blob/470854df3afee2e9d0494e3b436ed677eded4b52/tools/indoor_converter.py#L56-L57

2) Run `tools/create_data.py` to generate `uniseg3d_infos_train.pkl`. The generated `uniseg3d_infos_train.pkl` contains ScanNet dataset information without text tokens and pseudo mask labels.

3) Write text tokens to `uniseg3d_infos_train.pkl`:
- Filter out text prompts in the ScanRefer describing objects that are not annotated in ScanNet20.
- Feed the kept text prompts to [CLIP tokenizer](https://github.com/dk-liang/UniSeg3D/blob/470854df3afee2e9d0494e3b436ed677eded4b52/uniseg3d/openclip_backbone.py#L44C9-L44C66) and obtain text tokens.
- Write the obtained text tokens to the `uniseg3d_infos_train.pkl` generated in step 2. Refer to the formats of the released `uniseg3d_infos_train.pkl` file.

4) Write pseudo mask labels to `uniseg3d_infos_train.pkl`:
- Follow [SAM3D](https://github.com/Pointcept/SegmentAnything3D) to generate pseudo mask labels.
- Filter out all objects (including instances and stuff) annotated in ScanNet20 from the generated pseudo mask labels, as the annotated masks must be more reliable than the pseudo labels.
- Write the pseudo masks to the `uniseg3d_infos_train.pkl` generated in step 2. Refer to the formats of the released `uniseg3d_infos_train.pkl` file.
